// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsmeokzfaspdlmijnrnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbWVva3pmYXNwZGxtaWpucm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODEwMDEsImV4cCI6MjA2MjM1NzAwMX0.ss0xACSAQh0wuAUHu4gkbHwddMbk_CkVxcKJf2A6N_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);